// <auto-generated />
namespace ProjetGestionStock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Update_commande_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_commande_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202102182054132_Update_commande_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
